---
go_arch_map:
  # i386: '386'
  x86_64: 'amd64'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
_alertmanager_binary_install_dir: '/usr/local/bin'

# The expected location of the amtool configuration file
_alertmanager_amtool_config_dir: '/etc/amtool'
