- name: Copy database dump file
  copy:
    src: "{{ mysql_dump }}"
    dest: /tmp
    mode: 0664

- name: Restore database
  community.mysql.mysql_db:
    name: "wordpress"
    state: import
    target: "/tmp/{{ mysql_dump }}"
    # force: yes
  when:
    - mysql_replication_role != 'slave'
