---
nginx_revproxy_certbot_auto: false
# Remove WebRoot Sites
nginx_revproxy_remove_webroot_sites: true
# De-activate Sites
nginx_revproxy_de_activate_sites: true

nginx_revproxy_sites:                                         # List of sites to reverse proxy
  netology.simonof.info:                                                # Domain name
    domains:                                                  # List of server_name aliases
      - netology.simonof.info
    upstreams:
      - { backend_address: 10.0.1.16, backend_port: 443 }
    ssl: true                                                 # Set to True if you want to redirect http to https
    # listen_ssl: 443
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                        # Set to True if you want use letsencrypt
    letsencrypt_email: "asmo12@gmail.com"                                     # Set email for letencrypt cert
    client_max_body_size: "2048M"
    proxy_read_timeout: "360"
    backend_protocol: https

  default:                                                    # Set default site to return 444 (Connection Closed Without Response)
    ssl: true                                                # Set to True if you want to redirect http to https
    letsencrypt: false

  www.netology.simonof.info:                                                # Domain name
    domains:                                                  # List of server_name aliases
      - www.netology.simonof.info
    upstreams:
      - { backend_address: 10.0.1.16, backend_port: 80 }
    listen: 80
    # listen_ssl: 443
    ssl: false                                                # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true                                         # Set to True if you want use letsencrypt
    letsencrypt_email: "asmo12@gmail.com"                                     # Set email for letencrypt cert
    client_max_body_size: "2048M"
    proxy_read_timeout: "360"

  gitlab.netology.simonof.info:
    domains:                                                  # List of server_name aliases
      - gitlab.netology.simonof.info
    upstreams:
      - { backend_address: 10.0.1.19, backend_port: 443 }
    listen: 80
    listen_ssl: 443
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true
    letsencrypt_email: "asmo12@gmail.com"
    client_max_body_size: "2048M"
    proxy_read_timeout: "360"
    backend_protocol: https

  grafana.netology.simonof.info:
    domains:                                                  # List of server_name aliases
      - grafana.netology.simonof.info
    upstreams:
      - { backend_address: 10.0.1.21, backend_port: 3000 }
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true
    letsencrypt_email: "asmo12@gmail.com"
    client_max_body_size: "2048M"
    proxy_read_timeout: "360"
    backend_protocol: https

  prometheus.netology.simonof.info:
    domains:                                                  # List of server_name aliases
      - prometheus.netology.simonof.info
    upstreams:
      - { backend_address: 10.0.1.21, backend_port: 9090 }
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true
    letsencrypt_email: "asmo12@gmail.com"
    client_max_body_size: "2048M"
    proxy_read_timeout: "360"
    backend_protocol: https

  alertmanager.netology.simonof.info:
    domains:                                                  # List of server_name aliases
      - alertmanager.netology.simonof.info
    upstreams:
      - { backend_address: 10.0.1.21, backend_port: 9093 }
    ssl: true                                                 # Set to True if you want to redirect http to https
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
    letsencrypt: true
    letsencrypt_email: "asmo12@gmail.com"
    client_max_body_size: "2048M"
    proxy_read_timeout: "360"
    backend_protocol: https
