---
- include: preflight.yml

- include: install.yml
  become: true

- import_tasks: selinux.yml
  become: true
  when: ansible_selinux.status == "enabled"

- include: configure.yml
  become: true

- name: ensure alertmanager service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: alertmanager
    state: started
    enabled: true

- name: flush_handlers
  meta: flush_handlers
