---
- name: Install selinux python packages [clearlinux]
  package:
    name: sysadmin-basic
    state: present
  register: _install_selinux_packages
  until: _install_selinux_packages is success
  retries: 5
  delay: 2
  when:
    - ansible_distribution | lower == "clearlinux"
