---

- name: test if gitlab_runner_name is set correctly
  assert:
    that:
      - gitlab_runner_name is defined
      - gitlab_runner_name is string
    quiet: true

- name: test if gitlab_runner_token is set correctly
  assert:
    that:
      - gitlab_runner_token is string
    quiet: true
  when:
    - gitlab_runner_token is defined

- name: test if gitlab_runner_url is set correctly
  assert:
    that:
      - gitlab_runner_url is defined
      - gitlab_runner_url is string
    quiet: true

- name: test if gitlab_runner_tags is set correctly
  assert:
    that:
      - gitlab_runner_tags is iterable
    quiet: true
  when:
    - gitlab_runner_tags is defined

- name: test if gitlab_runner_executor is set correctly
  assert:
    that:
      - gitlab_runner_executor is string
      - gitlab_runner_executor in [ "ssh", "shell", "parallels", "virtualbox", "docker", "docker_machine", "kubernetes", "custom" ]
    quiet: true

- name: test if gitlab_runner_docker_image is set correctly
  assert:
    that:
      - gitlab_runner_docker_image is defined
      - gitlab_runner_docker_image is string
    quiet: true
  when:
    - gitlab_runner_executor == "docker"

- name: test if gitlab_runner_version is set correctly
  assert:
    that:
      - gitlab_runner_version is defined
      - gitlab_runner_version is string
    quiet: true
