---
- name: alerting rules file
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
  notify:
    - reload prometheus

# - name: Check if d folder is empty before proceeding
#   find:
#     paths: 'c/d/'
#   register: filesFound
# - fail:
#      msg: 'The d folder is not empty.'
#   when: filesFound.matched > 0
# - debug:
#     msg: 'The d folder is empty. Proceeding.'

- name: copy custom alerting rule files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  with_fileglob: "{{ prometheus_alert_rules_files }}"
  notify:
    - reload prometheus

- name: configure prometheus
  template:
    src: "{{ prometheus_config_file }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0644
    validate: "{{ _prometheus_binary_install_dir }}/promtool check config %s"
  notify:
    - reload prometheus

- name: configure prometheus nodes
  template:
    src: "{{ prometheus_nodes_file }}"
    dest: "{{ prometheus_config_dir }}/file_sd/node.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0644
  #   validate: "{{ _prometheus_binary_install_dir }}/promtool check web-config %s"
  # notify:
  #   - reload prometheus

- name: configure prometheus web-config
  template:
    src: "{{ prometheus_web_config_file }}"
    dest: "{{ prometheus_config_dir }}/web-config.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0644
    validate: "{{ _prometheus_binary_install_dir }}/promtool check web-config %s"
  notify:
    - reload prometheus

- name: configure prometheus static targets
  copy:
    content: |
      #jinja2: lstrip_blocks: True
      {{ item.value | to_nice_yaml(indent=2) }}
    dest: "{{ prometheus_config_dir }}/file_sd/{{ item.key }}.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0644
  with_dict: "{{ prometheus_targets }}"
  when: prometheus_targets != {}

- name: copy prometheus custom static targets
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/file_sd/"
    force: true
    owner: root
    group: prometheus
    mode: 0644
  with_fileglob: "{{ prometheus_static_targets_files }}"
