---
# defaults file for gitlab_runner

# These are the setting you need to register a runner.
gitlab_runner_token: 'cY7j8ScbRzyB14J92pPz'
# gitlab_runner_token: ''

# The name as shown in the GitLab webinterface.
gitlab_runner_name: "{{ ansible_host }}" # ansible_fqdn

# The URL to register the runner to.
gitlab_runner_url: "https://gitlab.{{ domain }}/"

# The list of tags.
gitlab_runner_tags: []

# The type of executor. Choose from: "ssh", "shell", "parallels", "virtualbox",
# "docker", "docker_machine", "kubernetes" or "custom"
gitlab_runner_executor: shell

# The docker image to run.
gitlab_runner_docker_image: "alpine:latest"

# The version of the GitLab runner to install.
gitlab_runner_version: "14.7.0"

gitlab_domain: "gitlab.{{ domain }}"
