---
cloud:
  children:
    proxys:
    apps:
    dbs:
    gits:
    mons:

proxys:
  hosts:
    proxy:
      ansible_host: 51.250.83.227

apps:
  hosts:
    app:
      ansible_host: 10.0.1.16

dbs:
  hosts:
    db01:
      ansible_host: 10.0.1.17
      mysql_server_id: 1
      mysql_replication_role: master
    db02:
      ansible_host: 10.0.1.18
      mysql_server_id: 2
      mysql_replication_role: slave

gits:
  hosts:
    gitlab:
      ansible_host: 10.0.1.19
    runner:
      ansible_host: 10.0.1.20

mons:
  hosts:
    monitoring:
      ansible_host: 10.0.1.21 
